### ISSUE TITLE
Unexpected token 'import'

### ISSUE THREAD

**Issue by vanillagranilla** [massimocode/amazon-ses-notification-processor#1]
Does this require a specific version of node?  I've  installed 6.2.2 straight from the website, but I get this output when running 

```
>node lib/index.ts

/home/blah/git/amazon-ses-notification-processor/lib/index.ts:3
import * as AWS from 'aws-sdk';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

**Comment by massimocode** [comment]
I tried replying by email earlier today, looks like my response never made it on here!

The typescript needs to be compiled for it to run on Node. I have developed this on Node v4.2.2 and I am pretty sure it should work on Node v6.2.2.

In the mean time I have made several improvements to the repo. Take a look here: https://github.com/massimocode/amazon-ses-notification-processor/commit/44a11275a22908b19e3106569710769b6caa8889

As well as several other improvements, you should now be able to just type `npm fetch` or `npm parse` and the typescript compilation will take place before the script runs.

Let me know if you have any issues and I'll be happy to take a look!

**Comment by vanillagranilla** [comment]
Thanks for the quick reply!  I'm new to typescript with node, so apologies for the confusion.

Here's the output I get when running 'npm run fetch' - I've got the aws-sdk installed, but it can't find a number of modules.  I'm hoping I missed something simple again:

```
➜  amazon-ses-notification-processor git:(master) ✗ npm run fetch

> sesbounce@1.0.0 fetch /Users/jgronowski/git/amazon-ses-notification-processor
> node node_modules/typescript/bin/tsc && node lib/fetch.js

lib/base-processor.ts(1,27): error TS2307: Cannot find module 'sqs-consumer'.
lib/base-processor.ts(2,22): error TS2307: Cannot find module 'aws-sdk'.
lib/base-processor.ts(10,18): error TS2503: Cannot find namespace 'NodeJS'.
lib/bounce-processor.ts(1,27): error TS2307: Cannot find module 'sqs-consumer'.
lib/bounce-processor.ts(2,22): error TS2307: Cannot find module 'aws-sdk'.
lib/complaint-processor.ts(1,27): error TS2307: Cannot find module 'sqs-consumer'.
lib/complaint-processor.ts(2,22): error TS2307: Cannot find module 'aws-sdk'.
lib/fetch.ts(3,22): error TS2307: Cannot find module 'aws-sdk'.
lib/fetch.ts(4,23): error TS2307: Cannot find module 'path'.
lib/fetch.ts(10,14): error TS2304: Cannot find name 'require'.
lib/fetch.ts(12,35): error TS2304: Cannot find name '__dirname'.
lib/fetch.ts(13,21): error TS2304: Cannot find name 'process'.
lib/result-recorder.ts(3,21): error TS2307: Cannot find module 'fs'.
lib/result-recorder.ts(4,23): error TS2307: Cannot find module 'path'.
lib/result-recorder.ts(15,24): error TS2304: Cannot find name 'require'.
lib/result-recorder.ts(39,30): error TS2304: Cannot find name '__dirname'.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "fetch"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE
npm ERR! sesbounce@1.0.0 fetch: `node node_modules/typescript/bin/tsc && node lib/fetch.js`
npm ERR! Exit status 2
```

**Comment by massimocode** [comment]
Sorry about that, my mistake!

Basically TypeScript uses these metadata files called type definitions (.d.ts files) so be able to tell it what types the dependencies you are using are. This way, it can perform static analysis to ensure you have used your dependencies correctly.

I forgot to check in the typings folder which contains the type definition files for Node, AWS SDK and SES Consumer (dependencies I am using), hence why the error above is saying these modules cannot be found.

I've checked them in now so you can grab latest and give it another shot!

**Comment by vanillagranilla** [comment]
Success!  Just what I was looking for.  Thanks!
